#TODO collect all parameters and add placeholders
# this only applies to models and things that need paths as well as database stuff but not secrets

literature:
  vl_model:
    model:
      name: "Qwen/Qwen2.5-VL-3B-Instruct"
      config:
        cache_dir: "/home/alper/Documents/packages/ccm_benchmate/benchmate/models/hf_models"
    processor:
        name : "Qwen/Qwen2.5-VL-3B-Instruct"
        config:
          cache_dir: "/home/alper/Documents/packages/ccm_benchmate/benchmate/models/hf_models"
    table_prompt: "You are an expert researcher who is responsible for reading and interpreting scientific tables. For a given table from a scientific paper interpret the table. Do not provide comments on whether the table is well done or not. Do not provide extra text on describing that you are looking at table from a scientific publication. Give an overall conclusion about what the tables tells us."
    figure_prompt: "You are an expert researcher who is responsible for reading and interpreting scientific figures. For a given figure from a scientific paper interpret the figure. Do not provide comments on whether the figure is well done or not. Do not provide extra text on describing that you are looking at figure from a scientific publication. Whenever possible very briefly describe each sections of the figure and then give an overall conclusion about what the figure tells us. "
  lp_model:
      model_path: "/home/alper/Documents/packages/ccm_benchmate/benchmate/models/lp_model/model_final.pth"
      config_path: "/home/alper/Documents/packages/ccm_benchmate/benchmate/models/lp_model/config.yaml"
  text_embedding_model:
      name: "Qwen/Qwen3-Embedding-0.6B"
      config:
        cache_folder: "/home/alper/Documents/packages/ccm_benchmate/benchmate/models/hf_models"
  image_embedding_model:
      model:
        name: "vidore/colpali-v1.3"
        config:
          cache_dir: "/home/alper/Documents/packages/ccm_benchmate/benchmate/models/hf_models"
      processor:
          name: "vidore/colpali-v1.3"
          config:
            cache_dir: "/home/alper/Documents/packages/ccm_benchmate/benchmate/models/hf_models"
  chunker_model:
      model: "/home/alper/Documents/packages/ccm_benchmate/benchmate/models/m2v_model/"
      min_sentences: 1
      return_type: "texts"
      threshold: "auto"
      chunk_size: 100


knowledge_base:
  name : null
  host: null
  port: null
  username: null
  password: null